n = input('Digite algo:')
print('O tipo primitivo desse valor é', type(n))
print('É composto apenas de espaços?', n.isspace())
print('É numérico?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('Está somente em maiúsculas?', n.isupper())
print('Está somente em minúsculas?', n.islower())
print('Pode ser impresso?', n.isprintable())
print('É decimal?', n.isdecimal())
print('É somente dígito?', n.isdigit())
print('É título?', n.istitle())
